# Indexing and Selection

## Problem Statement

In any data analysis, we rarely work with the entire dataset at once. Indexing is the process of selecting specific rows and columns from a DataFrame. In this notebook we explore the three main ways to index and select data in Pandas: the indexing operator `[]`, label-based selection with `.loc[]`, and position-based selection with `.iloc[]`. We also look at `idxmax()` and `idxmin()` to locate rows holding the maximum and minimum values of a column.

## Import Libraries

In [ ]:
import pandas as pd

## Load the Dataset

Load your dataset here. Replace the placeholder below with your actual data source. The examples in this notebook assume `Match ID` is set as the index label.

In [ ]:
# TODO: Load your dataset here
df = pd.read_csv('sample_ipl_dataset.csv')

#Set the index label used for label-based selection
df = df.set_index('Match ID')

df

,Batter,Team,Venue,Method
Match ID,,,,
1359477,KL Rahul,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Bowled
829795,CH Gayle,Royal Challengers Bangalore,Wankhede Stadium,Caught
1178406,V Kohli,Royal Challengers Bangalore,Wankhede Stadium,Caught
336010,A Chopra,Kolkata Knight Riders,Eden Gardens,Caught
1082610,CH Gayle,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium,Bowled
733975,M Vijay,Delhi Daredevils,Feroz Shah Kotla,Caught
419132,RS Bopara,Kings XI Punjab,Brabourne Stadium,LBW
1082624,AM Rahane,Rising Pune Supergiant,Maharashtra Cricket Association Stadium,Caught
829779,DR Smith,Chennai Super Kings,MA Chidambaram Stadium,Bowled
501254,BB McCullum,Kochi Tuskers Kerala,Holkar Cricket Stadium,Caught
598032,PA Reddy,Sunrisers Hyderabad,Sawai Mansingh Stadium,LBW
1175372,PA Patel,Royal Challengers Bangalore,M.Chinnaswamy Stadium,Caught
1136606,AD Hales,Sunrisers Hyderabad,Maharashtra Cricket Association Stadium,Bowled
1254066,RG Sharma,Mumbai Indians,MA Chidambaram Stadium,LBW
548373,AM Rahane,Rajasthan Royals,Rajiv Gandhi International Stadium,Stumped
598039,SR Tendulkar,Mumbai Indians,Rajiv Gandhi International Stadium,Caught
392199,BB McCullum,Kolkata Knight Riders,Kingsmead,Caught
501261,M Vijay,Chennai Super Kings,MA Chidambaram Stadium,Run Out
336004,YV Takawale,Mumbai Indians,Dr DY Patil Sports Academy,Stumped
733993,Q de Kock,Delhi Daredevils,Feroz Shah Kotla,LBW
548367,CH Gayle,Royal Challengers Bangalore,M Chinnaswamy Stadium,Caught
548337,JD Ryder,Pune Warriors,Subrata Roy Sahara Stadium,Stumped
1136613,JC Archer,Rajasthan Royals,Sawai Mansingh Stadium,Caught
829791,M Vijay,Kings XI Punjab,Eden Gardens,Caught
980927,KL Rahul,Royal Challengers Bangalore,Wankhede Stadium,Caught
548315,JH Kallis,Kolkata Knight Riders,M Chinnaswamy Stadium,Caught
1082647,RA Tripathi,Rising Pune Supergiant,Wankhede Stadium,Bowled
980929,AJ Finch,Gujarat Lions,Saurashtra Cricket Association Stadium,Bowled
548359,SE Marsh,Kings XI Punjab,Rajiv Gandhi International Stadium,Bowled
501257,AC Gilchrist,Kings XI Punjab,Himachal Pradesh Cricket Association Stadium,Caught

Inspect the first few rows.

In [ ]:
df.head()

,Batter,Team,Venue,Method
Match ID,,,,
1359477,KL Rahul,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Bowled
829795,CH Gayle,Royal Challengers Bangalore,Wankhede Stadium,Caught
1178406,V Kohli,Royal Challengers Bangalore,Wankhede Stadium,Caught
336010,A Chopra,Kolkata Knight Riders,Eden Gardens,Caught
1082610,CH Gayle,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium,Bowled

Check the shape of the DataFrame.

In [ ]:
df.shape

(30, 4)

## Indexing Operator `[]`

The `[]` operator is the simplest way to access data in a DataFrame. It is mainly used for column selection.

**Selecting a Single Column:** passing a single column name as a string returns a Series.

In [ ]:
df['Batter']

Match ID
1359477        KL Rahul
829795         CH Gayle
1178406         V Kohli
336010         A Chopra
1082610        CH Gayle
733975          M Vijay
419132        RS Bopara
1082624       AM Rahane
829779         DR Smith
501254      BB McCullum
598032         PA Reddy
1175372        PA Patel
1136606        AD Hales
1254066       RG Sharma
548373        AM Rahane
598039     SR Tendulkar
392199      BB McCullum
501261          M Vijay
336004      YV Takawale
733993        Q de Kock
548367         CH Gayle
548337         JD Ryder
1136613       JC Archer
829791          M Vijay
980927         KL Rahul
548315        JH Kallis
1082647     RA Tripathi
980929         AJ Finch
548359         SE Marsh
501257     AC Gilchrist
Name: Batter, dtype: object

**Selecting Multiple Columns:** passing a list of column names returns a DataFrame.

In [ ]:
df[['Batter', 'Team', 'Method']]

                Batter                         Team   Method
Match ID
1359477       KL Rahul         Lucknow Super Giants   Bowled
829795        CH Gayle  Royal Challengers Bangalore   Caught
1178406        V Kohli  Royal Challengers Bangalore   Caught
336010        A Chopra        Kolkata Knight Riders   Caught
1082610       CH Gayle  Royal Challengers Bangalore   Bowled
733975         M Vijay             Delhi Daredevils   Caught
419132       RS Bopara              Kings XI Punjab      LBW
1082624      AM Rahane       Rising Pune Supergiant   Caught
829779        DR Smith          Chennai Super Kings   Bowled
501254     BB McCullum         Kochi Tuskers Kerala   Caught
598032        PA Reddy          Sunrisers Hyderabad      LBW
1175372       PA Patel  Royal Challengers Bangalore   Caught
1136606       AD Hales          Sunrisers Hyderabad   Bowled
1254066      RG Sharma               Mumbai Indians      LBW
548373       AM Rahane             Rajasthan Royals  Stumped
598039    SR Tendulkar               Mumbai Indians   Caught
392199     BB McCullum        Kolkata Knight Riders   Caught
501261         M Vijay          Chennai Super Kings  Run Out
336004     YV Takawale               Mumbai Indians  Stumped
733993       Q de Kock             Delhi Daredevils      LBW
548367        CH Gayle  Royal Challengers Bangalore   Caught
548337        JD Ryder                Pune Warriors  Stumped
1136613      JC Archer             Rajasthan Royals   Caught
829791         M Vijay              Kings XI Punjab   Caught
980927        KL Rahul  Royal Challengers Bangalore   Caught
548315       JH Kallis        Kolkata Knight Riders   Caught
1082647    RA Tripathi       Rising Pune Supergiant   Bowled
980929        AJ Finch                Gujarat Lions   Bowled
548359        SE Marsh              Kings XI Punjab   Bowled
501257    AC Gilchrist              Kings XI Punjab   Caught

While `[]` is convenient for selecting columns, it lacks row selection and customized index handling. This is where `.loc[]` and `.iloc[]` come in.

## `.loc[]` - Label-based Selection

`.loc[]` selects data by labels (row/column names). It supports slicing and boolean conditions, and can handle numerical indices when they are set as row labels.

**Syntax:**
```python
df.loc[row_label, column_label]
```

**Single Row Selection:** select a single row by its index label.

In [ ]:
df.loc[1178406]

Batter                        V Kohli
Team      Royal Challengers Bangalore
Venue                Wankhede Stadium
Method                         Caught
Name: 1178406, dtype: object

In [ ]:
df.loc[[548315]]

             Batter                   Team                  Venue  Method
Match ID
548315    JH Kallis  Kolkata Knight Riders  M Chinnaswamy Stadium  Caught

**Multiple Row Selection:** select multiple rows by their index labels.

In [ ]:
df.loc[[829795, 1178406]]

            Batter                         Team             Venue  Method
Match ID
829795    CH Gayle  Royal Challengers Bangalore  Wankhede Stadium  Caught
1178406    V Kohli  Royal Challengers Bangalore  Wankhede Stadium  Caught

**Single Column Selection:** select one column across all rows.

In [ ]:
df.loc[:, 'Team']

Match ID
1359477           Lucknow Super Giants
829795     Royal Challengers Bangalore
1178406    Royal Challengers Bangalore
336010           Kolkata Knight Riders
1082610    Royal Challengers Bangalore
733975                Delhi Daredevils
419132                 Kings XI Punjab
1082624         Rising Pune Supergiant
829779             Chennai Super Kings
501254            Kochi Tuskers Kerala
598032             Sunrisers Hyderabad
1175372    Royal Challengers Bangalore
1136606            Sunrisers Hyderabad
1254066                 Mumbai Indians
548373                Rajasthan Royals
598039                  Mumbai Indians
392199           Kolkata Knight Riders
501261             Chennai Super Kings
336004                  Mumbai Indians
733993                Delhi Daredevils
548367     Royal Challengers Bangalore
548337                   Pune Warriors
1136613               Rajasthan Royals
829791                 Kings XI Punjab
980927     Royal Challengers Bangalore
548315           Kolkata Knight Riders
1082647         Rising Pune Supergiant
980929                   Gujarat Lions
548359                 Kings XI Punjab
501257                 Kings XI Punjab
Name: Team, dtype: object

**Multiple Columns Selection:** select multiple columns across all rows.

In [ ]:
df.loc[:, ['Batter', 'Team']]

                Batter                         Team
Match ID
1359477       KL Rahul         Lucknow Super Giants
829795        CH Gayle  Royal Challengers Bangalore
1178406        V Kohli  Royal Challengers Bangalore
336010        A Chopra        Kolkata Knight Riders
1082610       CH Gayle  Royal Challengers Bangalore
733975         M Vijay             Delhi Daredevils
419132       RS Bopara              Kings XI Punjab
1082624      AM Rahane       Rising Pune Supergiant
829779        DR Smith          Chennai Super Kings
501254     BB McCullum         Kochi Tuskers Kerala
598032        PA Reddy          Sunrisers Hyderabad
1175372       PA Patel  Royal Challengers Bangalore
1136606       AD Hales          Sunrisers Hyderabad
1254066      RG Sharma               Mumbai Indians
548373       AM Rahane             Rajasthan Royals
598039    SR Tendulkar               Mumbai Indians
392199     BB McCullum        Kolkata Knight Riders
501261         M Vijay          Chennai Super Kings
336004     YV Takawale               Mumbai Indians
733993       Q de Kock             Delhi Daredevils
548367        CH Gayle  Royal Challengers Bangalore
548337        JD Ryder                Pune Warriors
1136613      JC Archer             Rajasthan Royals
829791         M Vijay              Kings XI Punjab
980927        KL Rahul  Royal Challengers Bangalore
548315       JH Kallis        Kolkata Knight Riders
1082647    RA Tripathi       Rising Pune Supergiant
980929        AJ Finch                Gujarat Lions
548359        SE Marsh              Kings XI Punjab
501257    AC Gilchrist              Kings XI Punjab

**Row Slicing:** select a range of rows using labels (inclusive of the end label).

In [ ]:
df.loc[829795:733975]

,Batter,Team,Venue,Method
Match ID,,,,
829795,CH Gayle,Royal Challengers Bangalore,Wankhede Stadium,Caught
1178406,V Kohli,Royal Challengers Bangalore,Wankhede Stadium,Caught
336010,A Chopra,Kolkata Knight Riders,Eden Gardens,Caught
1082610,CH Gayle,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium,Bowled
733975,M Vijay,Delhi Daredevils,Feroz Shah Kotla,Caught

**Column Slicing:** select a range of columns using column labels.

In [ ]:
df.loc[:, 'Batter':'Venue']

,Batter,Team,Venue
Match ID,,,
1359477,KL Rahul,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
829795,CH Gayle,Royal Challengers Bangalore,Wankhede Stadium
1178406,V Kohli,Royal Challengers Bangalore,Wankhede Stadium
336010,A Chopra,Kolkata Knight Riders,Eden Gardens
1082610,CH Gayle,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium
733975,M Vijay,Delhi Daredevils,Feroz Shah Kotla
419132,RS Bopara,Kings XI Punjab,Brabourne Stadium
1082624,AM Rahane,Rising Pune Supergiant,Maharashtra Cricket Association Stadium
829779,DR Smith,Chennai Super Kings,MA Chidambaram Stadium
501254,BB McCullum,Kochi Tuskers Kerala,Holkar Cricket Stadium
598032,PA Reddy,Sunrisers Hyderabad,Sawai Mansingh Stadium
1175372,PA Patel,Royal Challengers Bangalore,M.Chinnaswamy Stadium
1136606,AD Hales,Sunrisers Hyderabad,Maharashtra Cricket Association Stadium
1254066,RG Sharma,Mumbai Indians,MA Chidambaram Stadium
548373,AM Rahane,Rajasthan Royals,Rajiv Gandhi International Stadium
598039,SR Tendulkar,Mumbai Indians,Rajiv Gandhi International Stadium
392199,BB McCullum,Kolkata Knight Riders,Kingsmead
501261,M Vijay,Chennai Super Kings,MA Chidambaram Stadium
336004,YV Takawale,Mumbai Indians,Dr DY Patil Sports Academy
733993,Q de Kock,Delhi Daredevils,Feroz Shah Kotla
548367,CH Gayle,Royal Challengers Bangalore,M Chinnaswamy Stadium
548337,JD Ryder,Pune Warriors,Subrata Roy Sahara Stadium
1136613,JC Archer,Rajasthan Royals,Sawai Mansingh Stadium
829791,M Vijay,Kings XI Punjab,Eden Gardens
980927,KL Rahul,Royal Challengers Bangalore,Wankhede Stadium
548315,JH Kallis,Kolkata Knight Riders,M Chinnaswamy Stadium
1082647,RA Tripathi,Rising Pune Supergiant,Wankhede Stadium
980929,AJ Finch,Gujarat Lions,Saurashtra Cricket Association Stadium
548359,SE Marsh,Kings XI Punjab,Rajiv Gandhi International Stadium
501257,AC Gilchrist,Kings XI Punjab,Himachal Pradesh Cricket Association Stadium

**Conditional Row Selection:** select rows that satisfy a given condition.

In [ ]:
df.loc[df['Method'] == 'Bowled']

,Batter,Team,Venue,Method
Match ID,,,,
1359477,KL Rahul,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Bowled
1082610,CH Gayle,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium,Bowled
829779,DR Smith,Chennai Super Kings,MA Chidambaram Stadium,Bowled
1136606,AD Hales,Sunrisers Hyderabad,Maharashtra Cricket Association Stadium,Bowled
1082647,RA Tripathi,Rising Pune Supergiant,Wankhede Stadium,Bowled
980929,AJ Finch,Gujarat Lions,Saurashtra Cricket Association Stadium,Bowled
548359,SE Marsh,Kings XI Punjab,Rajiv Gandhi International Stadium,Bowled

In [ ]:
df.loc[df['Method'] != 'lbw']

,Batter,Team,Venue,Method
Match ID,,,,
1359477,KL Rahul,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Bowled
829795,CH Gayle,Royal Challengers Bangalore,Wankhede Stadium,Caught
1178406,V Kohli,Royal Challengers Bangalore,Wankhede Stadium,Caught
336010,A Chopra,Kolkata Knight Riders,Eden Gardens,Caught
1082610,CH Gayle,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium,Bowled
733975,M Vijay,Delhi Daredevils,Feroz Shah Kotla,Caught
419132,RS Bopara,Kings XI Punjab,Brabourne Stadium,LBW
1082624,AM Rahane,Rising Pune Supergiant,Maharashtra Cricket Association Stadium,Caught
829779,DR Smith,Chennai Super Kings,MA Chidambaram Stadium,Bowled
501254,BB McCullum,Kochi Tuskers Kerala,Holkar Cricket Stadium,Caught
598032,PA Reddy,Sunrisers Hyderabad,Sawai Mansingh Stadium,LBW
1175372,PA Patel,Royal Challengers Bangalore,M.Chinnaswamy Stadium,Caught
1136606,AD Hales,Sunrisers Hyderabad,Maharashtra Cricket Association Stadium,Bowled
1254066,RG Sharma,Mumbai Indians,MA Chidambaram Stadium,LBW
548373,AM Rahane,Rajasthan Royals,Rajiv Gandhi International Stadium,Stumped
598039,SR Tendulkar,Mumbai Indians,Rajiv Gandhi International Stadium,Caught
392199,BB McCullum,Kolkata Knight Riders,Kingsmead,Caught
501261,M Vijay,Chennai Super Kings,MA Chidambaram Stadium,Run Out
336004,YV Takawale,Mumbai Indians,Dr DY Patil Sports Academy,Stumped
733993,Q de Kock,Delhi Daredevils,Feroz Shah Kotla,LBW
548367,CH Gayle,Royal Challengers Bangalore,M Chinnaswamy Stadium,Caught
548337,JD Ryder,Pune Warriors,Subrata Roy Sahara Stadium,Stumped
1136613,JC Archer,Rajasthan Royals,Sawai Mansingh Stadium,Caught
829791,M Vijay,Kings XI Punjab,Eden Gardens,Caught
980927,KL Rahul,Royal Challengers Bangalore,Wankhede Stadium,Caught
548315,JH Kallis,Kolkata Knight Riders,M Chinnaswamy Stadium,Caught
1082647,RA Tripathi,Rising Pune Supergiant,Wankhede Stadium,Bowled
980929,AJ Finch,Gujarat Lions,Saurashtra Cricket Association Stadium,Bowled
548359,SE Marsh,Kings XI Punjab,Rajiv Gandhi International Stadium,Bowled
501257,AC Gilchrist,Kings XI Punjab,Himachal Pradesh Cricket Association Stadium,Caught

**Row and Column Selection:** select specific rows and specific columns together.

In [ ]:
df.loc[[829779, 1175372], 'Batter':'Venue']

            Batter                         Team                   Venue
Match ID
829779    DR Smith          Chennai Super Kings  MA Chidambaram Stadium
1175372   PA Patel  Royal Challengers Bangalore   M.Chinnaswamy Stadium

## `.iloc[]` - Position-based Indexing

`.iloc[]` selects data by integer index positions. Rows and columns are selected based on their numerical position in the DataFrame, using zero-based indexing.

**Syntax:**
```python
df.iloc[row_index, column_index]
```

**Single Row Selection:** select a single row by its position.

In [ ]:
df.iloc[2]

**Multiple Rows Selection:** select multiple rows by their positions.

In [ ]:
df.iloc[[0, 2, 3]]

,Batter,Team,Venue,Method
Match ID,,,,
1359477,KL Rahul,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Bowled
1178406,V Kohli,Royal Challengers Bangalore,Wankhede Stadium,Caught
336010,A Chopra,Kolkata Knight Riders,Eden Gardens,Caught

**Single Column Selection:** select one column by its position.

In [ ]:
df.iloc[:, 3]

Match ID
1359477     Bowled
829795      Caught
1178406     Caught
336010      Caught
1082610     Bowled
733975      Caught
419132         LBW
1082624     Caught
829779      Bowled
501254      Caught
598032         LBW
1175372     Caught
1136606     Bowled
1254066        LBW
548373     Stumped
598039      Caught
392199      Caught
501261     Run Out
336004     Stumped
733993         LBW
548367      Caught
548337     Stumped
1136613     Caught
829791      Caught
980927      Caught
548315      Caught
1082647     Bowled
980929      Bowled
548359      Bowled
501257      Caught
Name: Method, dtype: object

**Multiple Columns Selection:** select multiple columns by their positions.

In [ ]:
df.iloc[:, [0, 3]]

                Batter   Method
Match ID
1359477       KL Rahul   Bowled
829795        CH Gayle   Caught
1178406        V Kohli   Caught
336010        A Chopra   Caught
1082610       CH Gayle   Bowled
733975         M Vijay   Caught
419132       RS Bopara      LBW
1082624      AM Rahane   Caught
829779        DR Smith   Bowled
501254     BB McCullum   Caught
598032        PA Reddy      LBW
1175372       PA Patel   Caught
1136606       AD Hales   Bowled
1254066      RG Sharma      LBW
548373       AM Rahane  Stumped
598039    SR Tendulkar   Caught
392199     BB McCullum   Caught
501261         M Vijay  Run Out
336004     YV Takawale  Stumped
733993       Q de Kock      LBW
548367        CH Gayle   Caught
548337        JD Ryder  Stumped
1136613      JC Archer   Caught
829791         M Vijay   Caught
980927        KL Rahul   Caught
548315       JH Kallis   Caught
1082647    RA Tripathi   Bowled
980929        AJ Finch   Bowled
548359        SE Marsh   Bowled
501257    AC Gilchrist   Caught

**Row Slicing:** select a range of rows by position (end position excluded).

In [ ]:
df.iloc[1:3]

            Batter                         Team             Venue  Method
Match ID
829795    CH Gayle  Royal Challengers Bangalore  Wankhede Stadium  Caught
1178406    V Kohli  Royal Challengers Bangalore  Wankhede Stadium  Caught

**Column Slicing:** select a range of columns by position.

In [ ]:
df.iloc[:, 1:3]

,Team,Venue
Match ID,,
1359477,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
829795,Royal Challengers Bangalore,Wankhede Stadium
1178406,Royal Challengers Bangalore,Wankhede Stadium
336010,Kolkata Knight Riders,Eden Gardens
1082610,Royal Challengers Bangalore,Saurashtra Cricket Association Stadium
733975,Delhi Daredevils,Feroz Shah Kotla
419132,Kings XI Punjab,Brabourne Stadium
1082624,Rising Pune Supergiant,Maharashtra Cricket Association Stadium
829779,Chennai Super Kings,MA Chidambaram Stadium
501254,Kochi Tuskers Kerala,Holkar Cricket Stadium
598032,Sunrisers Hyderabad,Sawai Mansingh Stadium
1175372,Royal Challengers Bangalore,M.Chinnaswamy Stadium
1136606,Sunrisers Hyderabad,Maharashtra Cricket Association Stadium
1254066,Mumbai Indians,MA Chidambaram Stadium
548373,Rajasthan Royals,Rajiv Gandhi International Stadium
598039,Mumbai Indians,Rajiv Gandhi International Stadium
392199,Kolkata Knight Riders,Kingsmead
501261,Chennai Super Kings,MA Chidambaram Stadium
336004,Mumbai Indians,Dr DY Patil Sports Academy
733993,Delhi Daredevils,Feroz Shah Kotla
548367,Royal Challengers Bangalore,M Chinnaswamy Stadium
548337,Pune Warriors,Subrata Roy Sahara Stadium
1136613,Rajasthan Royals,Sawai Mansingh Stadium
829791,Kings XI Punjab,Eden Gardens
980927,Royal Challengers Bangalore,Wankhede Stadium
548315,Kolkata Knight Riders,M Chinnaswamy Stadium
1082647,Rising Pune Supergiant,Wankhede Stadium
980929,Gujarat Lions,Saurashtra Cricket Association Stadium
548359,Kings XI Punjab,Rajiv Gandhi International Stadium
501257,Kings XI Punjab,Himachal Pradesh Cricket Association Stadium

**Row and Column Selection:** select rows and columns together by position.

In [ ]:
df.iloc[1:3, 0:3]

            Batter                         Team             Venue
Match ID
829795    CH Gayle  Royal Challengers Bangalore  Wankhede Stadium
1178406    V Kohli  Royal Challengers Bangalore  Wankhede Stadium

## `.loc[]` vs `.iloc[]`

| Aspect | `.loc[]` | `.iloc[]` |
|---|---|---|
| Selection basis | Labels (row/column names) | Integer positions |
| Indexing style | Label-based | Zero-based positional |
| Slicing end | Inclusive of end label | Excludes end position |
| Conditions | Supports boolean conditions | Positional only |

## `idxmax()` and `idxmin()`

These return the index label of the maximum and minimum values in a Series, letting us locate the full row where an extreme value occurs. Replace `'ColumnName'` with a numeric column from your dataset.

**`idxmax()`:** returns the index label of the maximum value in a column, used to locate the row where the highest value occurs.

In [ ]:
df.loc[df['Team'].idxmax()]

Batter                  PA Reddy
Team         Sunrisers Hyderabad
Venue     Sawai Mansingh Stadium
Method                       LBW
Name: 598032, dtype: object

**`idxmin()`:** returns the index label of the minimum value in a column, used to locate the row where the lowest value occurs.

In [ ]:
df.loc[df['Venue'].idxmin()]

Batter                                             KL Rahul
Team                                   Lucknow Super Giants
Venue     Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
Method                                               Bowled
Name: 1359477, dtype: object

## Conclusion

The `[]` operator is best for quick column selection. `.loc[]` selects by labels and supports slicing and boolean conditions, while `.iloc[]` selects by integer position. `idxmax()` and `idxmin()` combined with `.loc[]` let us retrieve the full row holding the maximum or minimum value of a column.